version: "3.9"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: keydb
      MYSQL_USER: keyuser
      MYSQL_PASSWORD: keypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3305:3305"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: